import { useEffect, useState } from "react";
import { usePublicClient } from "wagmi";
import type { Abi, Address } from "viem";
import { logger } from "@bun-eth/core";
import type { DeployedContractInfo, ContractName, DeployedContracts } from "./types";

const contractLogger = logger.child("contracts");

/**
 * Gets the deployed contract info from the generated deployments file
 * @param contractName - name of the contract
 * @returns the deployed contract info (address and ABI)
 */
export const useDeployedContractInfo = <TContractName extends ContractName>(
  contractName: TContractName
): DeployedContractInfo | undefined => {
  const [deployedContractInfo, setDeployedContractInfo] = useState<DeployedContractInfo | undefined>();
  const publicClient = usePublicClient();

  useEffect(() => {
    const loadContract = async () => {
      try {
        const chainId = publicClient?.chain?.id;

        if (!chainId) {
          contractLogger.debug("Chain ID not available yet");
          return;
        }

        // Dynamic import of deployed contracts
        // This will be generated by the foundry-deployer package
        const deployedContracts = await import("../../contracts/deployedContracts").catch(() => null);

        if (!deployedContracts) {
          contractLogger.debug("No deployed contracts file found");
          return;
        }

        const contracts = deployedContracts.default as DeployedContracts | undefined;
        const contract = contracts?.[chainId]?.[contractName];

        if (contract) {
          // Verify contract is deployed by checking bytecode
          const code = await publicClient?.getBytecode({ address: contract.address });

          if (code && code !== "0x") {
            setDeployedContractInfo({
              address: contract.address as Address,
              abi: contract.abi as Abi,
            });
          } else {
            contractLogger.warn(`Contract ${String(contractName)} not deployed at ${contract.address}`);
          }
        }
      } catch (error) {
        contractLogger.error("Error loading deployed contract info", error);
      }
    };

    loadContract();
  }, [contractName, publicClient]);

  return deployedContractInfo;
};
