services:
  # Anvil local Ethereum node (Foundry)
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: bun-eth-anvil
    ports:
      - "${ANVIL_PORT:-3002}:8545"
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    command: ["anvil", "--host", "0.0.0.0", "--port", "8545", "--block-time", "1"]
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://127.0.0.1:8545"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Bun-Eth API
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    container_name: bun-eth-api
    ports:
      - "${API_PORT:-3001}:3001"
    environment:
      PORT: 3001
      NODE_ENV: development
      ANVIL_NODE: http://anvil:8545  # Internal Docker network uses container port
      PRIVATE_KEY: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      CHAIN_ID: 31337
    depends_on:
      anvil:
        condition: service_healthy
    volumes:
      - ../apps/api:/app/apps/api
      - ../packages/core:/app/packages/core
    restart: unless-stopped

networks:
  default:
    name: bun-eth-network
