/**
 * Deployed contracts registry
 * This file is auto-generated by the foundry-deployer package
 *
 * Structure:
 * {
 *   [chainId]: {
 *     [contractName]: {
 *       address: "0x...",
 *       abi: [...]
 *     }
 *   }
 * }
 */

export default {};
